dist: trusty
sudo: false
language: none

service:
  - docker

script:
 - cd str
 - docker run --rm -it -v $PWD:/home/hrp2/sdk/workspace/product korosuke613/etrobo-docker makeRight
 - docker run --rm -it -v $PWD:/home/hrp2/sdk/workspace/product korosuke613/etrobo-docker makeLeft

notifications:
  email: false